export const SGP_TABLE_REGISTRO_INDIVIDUAL = 'SGP_TABLE_REGISTRO_INDIVIDUAL';
export const SGP_TABLE_REGISTRO_INDIVIDUAL_LINHA =
  'SGP_TABLE_REGISTRO_INDIVIDUAL_LINHA_';
export const SGP_TABLE_LISTA_ALUNOS = 'SGP_TABLE_LISTA_ALUNOS';
export const SGP_TABLE_LISTA_ALUNOS_AUSENCIA_COMPENSADA =
  'SGP_TABLE_LISTA_ALUNOS_AUSENCIA_COMPENSADA';
export const SGP_TABLE_OBJETIVOS_APRENDIZAGEM =
  'SGP_TABLE_OBJETIVOS_APRENDIZAGEM';
export const SGP_TABLE_OBJETIVOS_APRENDIZAGEM_ADICIONADOS =
  'SGP_TABLE_OBJETIVOS_APRENDIZAGEM_ADICIONADOS';
export const SGP_TABLE_LISTA_ALUNOS_ENCAMINHAMENTO_AEE =
  'SGP_TABLE_LISTA_ALUNOS_ENCAMINHAMENTO_AEE';
export const SGP_TABLE_LANCAMENTO_NOTAS = 'SGP_TABLE_LANCAMENTO_NOTAS';
export const SGP_TABLE_LANCAMENTO_NOTAS_LINHA =
  'SGP_TABLE_LANCAMENTO_NOTAS_LINHA';
export const SGP_TABLE_ENCAMINHAMENTO_NAAPA = 'SGP_TABLE_ENCAMINHAMENTO_NAAPA';
