export const SGP_TABLE_REGISTRO_INDIVIDUAL = 'SGP_TABLE_REGISTRO_INDIVIDUAL';
export const SGP_TABLE_REGISTRO_INDIVIDUAL_LINHA =
  'SGP_TABLE_REGISTRO_INDIVIDUAL_LINHA_';
export const SGP_TABLE_LISTA_ALUNOS = 'SGP_TABLE_LISTA_ALUNOS';
export const SGP_TABLE_LISTA_ALUNOS_AUSENCIA_COMPENSADA =
  'SGP_TABLE_LISTA_ALUNOS_AUSENCIA_COMPENSADA';
