export const SGP_TAB_PRIMEIRO_BIMESTRE = 'SGP_TAB_PRIMEIRO_BIMESTRE';
export const SGP_TAB_SEGUNDO_BIMESTRE = 'SGP_TAB_SEGUNDO_BIMESTRE';
export const SGP_TAB_TERCEIRO_BIMESTRE = 'SGP_TAB_TERCEIRO_BIMESTRE';
export const SGP_TAB_QUARTO_BIMESTRE = 'SGP_TAB_QUARTO_BIMESTRE';
