# example
stages:
  - name: Build
    when:
      branch: fix/pipeline-dev
      event: [ push, pull_request ]
    steps:
    - runScriptConfig:
        image: node:16-alpine
        shellScript: cd src/SME.SGP.WebClient/ && yarn install && yarn build
      env:
        NODE_OPTIONS: --max_old_space_size=4096

branch:
  include: [ master, release, release-r2, development, fix/pipeline-dev ]
  exclude: [ feature/*, story/* ]

timeout: 60