module.exports = {
  collectCoverage: true,
  coverageReporters: ['text', 'lcov', 'json', 'html'],
  coverageDirectory: 'coverage',
  preset: 'ts-jest',
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': 'babel-jest',
    '^.+\\.(svg|jpg|jpeg|png|woff|woff2|eot|ttf|otf)$': 'jest-transform-stub',
  },
  testEnvironment: 'jsdom',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^~/(.*)$': '<rootDir>/src/@legacy/$1',
    '\\.(svg|jpg|jpeg|png|woff|woff2|eot|ttf|otf)$': '<rootDir>/__mocks__/fileMock.js',
    '\\.(css|less|scss|css\\.js)$': 'identity-obj-proxy',
    '\\.(css|less|scss)$': 'identity-obj-proxy',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  collectCoverageFrom: [
    'src/@legacy/**/*.{js,jsx,ts,tsx}',
    'src/pages/**/*.{js,jsx,ts,tsx}',
    'src/components/**/*.{js,jsx,ts,tsx}',
    '!src/**/*.test.{js,jsx,ts,tsx}',
    '!src/**/__mocks__/**',
    '!src/**/*.css.js',
  ],
  coverageThreshold: {
    global: {
      branches: 1,
      functions: 1,
      lines: 1,
      statements: 1,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.js'],
  transformIgnorePatterns: [
    '/node_modules/(?!antd|my-library-dir)/',
    '/node_modules/(?!react-quill)/',
  ],
  globals: {
    'ts-jest': {
      isolatedModules: true,
    },
  },
  extensionsToTreatAsEsm: ['.ts', '.tsx', '.jsx'],
  coverageProvider: 'v8',
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/build/',
    '/dist/',
    '/__mocks__/',
    '/.*.d.ts$/',
    '/.*.config.js$/',
    '/.*.test.js$/',
    '/.*.css.js$/',
    '/src/index\\.tsx$',
    '/src/@types',
    '/src/app\\.tsx$',
    '/.*\\/style\\.js$',
  ],
};
