export const SGP_CKEDITOR_PARECER_COORDENACAO_PLANO_AEE =
  'SGP_CKEDITOR_PARECER_COORDENACAO_PLANO_AEE';
export const SGP_CKEDITOR_PARECER_CEFAI_PLANO_AEE =
  'SGP_CKEDITOR_PARECER_CEFAI_PLANO_AEE';
