const mockTabelaEncaminhamentos = [
  {
    id: 1,
    tipo: 'Individual',
    suspeitaViolencia: 'Sim',
    nomeAluno: 'BRAIAN LEONARDO DE SOUZA SANTOS',
    codigoAluno: '795630',
    ehMatriculadoTurmaPAP: false,
    turma: 'EI-7C',
    dataAberturaQueixaInicio: '2025-07-20',
    dataUltimoAtendimento: '2025-07-25',
    situacao: 'Em atendimento',
    ue: 'CEI DIRET BENEDICTO ROCHA, VER.',
  },
  {
    id: 2,
    tipo: 'Institucional',
    suspeitaViolencia: 'Não',
    nomeAluno: '-',
    codigoAluno: '-',
    ehMatriculadoTurmaPAP: false,
    turma: '-',
    dataAberturaQueixaInicio: '-',
    dataUltimoAtendimento: '-',
    situacao: 'Em atendimento',
    ue: 'EMEI PEDROSO DE MORAES',
  },
  {
    id: 3,
    tipo: 'Institucional',
    suspeitaViolencia: 'Não',
    nomeAluno: '-',
    codigoAluno: '-',
    ehMatriculadoTurmaPAP: false,
    turma: '-',
    dataAberturaQueixaInicio: '-',
    dataUltimoAtendimento: '-',
    situacao: 'Em atendimento',
    ue: 'EMEI PEDROSO DE MORAES',
  },
  {
    id: 4,
    tipo: 'Institucional',
    suspeitaViolencia: 'Sim',
    nomeAluno: '-',
    codigoAluno: '-',
    ehMatriculadoTurmaPAP: false,
    turma: '-',
    dataAberturaQueixaInicio: '-',
    dataUltimoAtendimento: '-',
    situacao: 'Acompanhado',
    ue: 'EMEI PEDROSO DE MORAES',
  },
  {
    id: 5,
    tipo: 'Individual',
    suspeitaViolencia: 'Não',
    nomeAluno: 'BRAIAN LEONARDO DE SOUZA SANTOS',
    codigoAluno: '795630',
    ehMatriculadoTurmaPAP: false,
    turma: 'EI-7C',
    dataAberturaQueixaInicio: '2025-07-20',
    dataUltimoAtendimento: '2025-07-25',
    situacao: 'Acompanhado',
    ue: 'EMEI PEDROSO DE MORAES',
  },
  {
    id: 6,
    tipo: 'Institucional',
    suspeitaViolencia: 'Não',
    nomeAluno: '-',
    codigoAluno: '-',
    ehMatriculadoTurmaPAP: false,
    turma: '-',
    dataAberturaQueixaInicio: '-',
    dataUltimoAtendimento: '-',
    situacao: 'Acompanhado',
    ue: 'EMEI PEDROSO DE MORAES',
  },
  {
    id: 7,
    tipo: 'Institucional',
    suspeitaViolencia: 'Não',
    nomeAluno: '-',
    codigoAluno: '-',
    ehMatriculadoTurmaPAP: false,
    turma: '-',
    dataAberturaQueixaInicio: '-',
    dataUltimoAtendimento: '-',
    situacao: 'Acompanhado',
    ue: 'EMEI PEDROSO DE MORAES',
  },
  {
    id: 8,
    tipo: 'Institucional',
    suspeitaViolencia: 'Não',
    nomeAluno: '-',
    codigoAluno: '-',
    ehMatriculadoTurmaPAP: false,
    turma: '-',
    dataAberturaQueixaInicio: '-',
    dataUltimoAtendimento: '-',
    situacao: 'Acompanhado',
    ue: 'EMEI PEDROSO DE MORAES',
  },
  {
    id: 9,
    tipo: 'Institucional',
    suspeitaViolencia: 'Não',
    nomeAluno: '-',
    codigoAluno: '-',
    ehMatriculadoTurmaPAP: false,
    turma: '-',
    dataAberturaQueixaInicio: '-',
    dataUltimoAtendimento: '-',
    situacao: 'Acompanhado',
    ue: 'EMEI PEDROSO DE MORAES',
  },
  {
    id: 10,
    tipo: 'Institucional',
    suspeitaViolencia: 'Não',
    nomeAluno: '-',
    codigoAluno: '-',
    ehMatriculadoTurmaPAP: false,
    turma: '-',
    dataAberturaQueixaInicio: '-',
    dataUltimoAtendimento: '-',
    situacao: 'Encerrado',
    ue: 'EMEI PEDROSO DE MORAES',
  },
];

export default mockTabelaEncaminhamentos;
