export const SGP_SELECT_COMPONENTE_CURRICULAR =
  'SGP_SELECT_COMPONENTE_CURRICULAR';
export const SGP_SELECT_ANO_LETIVO = 'SGP_SELECT_ANO_LETIVO';
export const SGP_SELECT_DRE = 'SGP_SELECT_DRE';
export const SGP_SELECT_UE = 'SGP_SELECT_UE';
export const SGP_SELECT_MODALIDADE = 'SGP_SELECT_MODALIDADE';
export const SGP_SELECT_SEMESTRE = 'SGP_SELECT_SEMESTRE';
export const SGP_SELECT_TURMA = 'SGP_SELECT_TURMA';
export const SGP_SELECT_BIMESTRE = 'SGP_SELECT_BIMESTRE';
export const SGP_SELECT_PERIODO_POR_COMPONENTE_CURRICULAR =
  'SGP_SELECT_PERIODO_POR_COMPONENTE_CURRICULAR';
export const SGP_SELECT_TIPO_PENDENCIA = 'SGP_SELECT_TIPO_PENDENCIA';
export const SGP_SELECT_NOME_TIPO_PENDENCIA = 'SGP_SELECT_NOME_TIPO_PENDENCIA';
export const SGP_SELECT_TIPO_AVALIACAO = 'SGP_SELECT_TIPO_AVALIACAO';
export const SGP_SELECT_NOME_AVALIACAO = 'SGP_SELECT_NOME_AVALIACAO';
export const SGP_SELECT_OPCAO_ESTUDANTE = 'SGP_SELECT_OPCAO_ESTUDANTE';
export const SGP_SELECT_MODELO_BOLETIM = 'SGP_SELECT_MODELO_BOLETIM';
export const SGP_SELECT_VISUALIZACAO = 'SGP_SELECT_VISUALIZACAO';
export const SGP_SELECT_FORMATO = 'SGP_SELECT_FORMATO';
export const SGP_SELECT_TIPO_CALENDARIO = 'SGP_SELECT_TIPO_CALENDARIO';
export const SGP_SELECT_TIPO_EVENTO = 'SGP_SELECT_TIPO_EVENTO';
export const SGP_SELECT_FALTAS_COMPENSACAO = 'SGP_SELECT_FALTAS_COMPENSACAO';
export const SGP_SELECT_ESTUDANTE_CRIANCA = 'SGP_SELECT_ESTUDANTE_CRIANCA';
export const SGP_SELECT_SITUACAO = 'SGP_SELECT_SITUACAO';
export const SGP_SELECT_RESPONSAVEL = 'SGP_SELECT_RESPONSAVEL';
export const SGP_SELECT_NOTA = 'SGP_SELECT_NOTA';
export const SGP_SELECT_PAAIS_DRE = 'SGP_SELECT_PAAIS_DRE';
export const SGP_SELECT_CONCEITO_FINAL = 'SGP_SELECT_CONCEITO_FINAL';
export const SGP_SELECT_PRIORIDADE = 'SGP_SELECT_PRIORIDADE';
export const SGP_SELECT_SITUACAO_ENCAMINHAMENTO =
  'SGP_SELECT_SITUACAO_ENCAMINHAMENTO';
export const SGP_SELECT_SITUACAO_PLANO = 'SGP_SELECT_SITUACAO_PLANO';
export const SGP_SELECT_PAAI_RESPONSAVEL = 'SGP_SELECT_PAAI_RESPONSAVEL';
export const SGP_SELECT_TIPO_DOCUMENTO = 'SGP_SELECT_TIPO_DOCUMENTO';
export const SGP_SELECT_CLASSIFICACAO_DOCUMENTO =
  'SGP_SELECT_CLASSIFICACAO_DOCUMENTO';
export const SGP_SELECT_SITUACAO_ENCAMINHAMENTO_AEE =
  'SGP_SELECT_SITUACAO_ENCAMINHAMENTO_AEE';
export const SGP_SELECT_PREENCHER_DADOS_RESPONSAVEIS = 'SGP_SELECT_IMPRIMIR_DADOS_REPONSAVEIS';
export const SGP_SELECT_PREENCHER_DATA_IMPRESSAO = 'SGP_SELECT_IMPRIMIR_DATA_IMPRESSAO';
