export const SGP_JODIT_EDITOR_DESCRICAO_JUSTIFICATIVA =
  'SGP_JODIT_EDITOR_DESCRICAO_JUSTIFICATIVA';
export const SGP_JODIT_EDITOR_CADASTRO_AVALIACAO_DESCRICAO =
  'SGP_JODIT_EDITOR_CADASTRO_AVALIACAO_DESCRICAO';
