export const SGP_INPUT_NUMBER_QUANTIDADE_AULAS =
  'SGP_INPUT_NUMBER_QUANTIDADE_AULAS';
export const SGP_INPUT_TEXT_NOME_EVENTO = 'SGP_INPUT_TEXT_NOME_EVENTO';
export const SGP_INPUT_CODIGO_EOL = 'SGP_INPUT_CODIGO_EOL';
export const SGP_INPUT_NOTA = 'SGP_INPUT_NOTA';
export const SGP_INPUT_NOTA_FINAL = 'SGP_INPUT_NOTA_FINAL';
export const SGP_INPUT_CONCEITO_FINAL = 'SGP_INPUT_CONCEITO_FINAL';
export const SGP_INPUT_JUSTIFIQUE_MOTIVO_DEVOLUCAO =
  'SGP_INPUT_JUSTIFIQUE_MOTIVO_DEVOLUCAO';
export const SGP_INPUT_NOME = 'SGP_INPUT_NOME';
export const SGP_INPUT_RF = 'SGP_INPUT_RF';
export const SGP_INPUT_NOME_ATIVIDADE = 'SGP_INPUT_NOME_ATIVIDADE';
export const SGP_INPUT_NOME_ESTUDANTE = 'SGP_INPUT_NOME_ESTUDANTE';
