export const SGP_MENU_ITEM_ORDENAR_MENOR_PARA_MAIOR =
  'SGP_MENU_ITEM_ORDENAR_MENOR_PARA_MAIOR';
export const SGP_MENU_ITEM_ORDENAR_MAIOR_PARA_MENOR =
  'SGP_MENU_ITEM_ORDENAR_MAIOR_PARA_MENOR';
export const SGP_MENU_ITEM_ORDENAR_ORDEM_ALFABETICA_A_Z =
  'SGP_MENU_ITEM_ORDENAR_ORDEM_ALFABETICA_A_Z';
export const SGP_MENU_ITEM_ORDENAR_ORDEM_ALFABETICA_Z_A =
  'SGP_MENU_ITEM_ORDENAR_ORDEM_ALFABETICA_Z_A';
