export const SGP_DATA_AULA = 'SGP_DATA_AULA';
export const SGP_DATE_SELECIONAR_DATA_NOVO_REGISTRO_INDIVIDUAL =
  'SGP_DATE_SELECIONAR_DATA_NOVO_REGISTRO_INDIVIDUAL';
export const SGP_DATE_SELECIONAR_DATA_INICIO_REGISTROS_ANTERIORES =
  'SGP_DATE_SELECIONAR_DATA_INICIO_REGISTROS_ANTERIORES';
export const SGP_DATE_SELECIONAR_DATA_FIM_REGISTROS_ANTERIORES =
  'SGP_DATE_SELECIONAR_DATA_FIM_REGISTROS_ANTERIORES';
