export const ANO_INICIO_REGISTRO_COLETIVO_NAAPA = 2024;
export const ANO_INICIO_MAPEAMENTO_ESTUDANTES = 2024;
export const ANO_INICIO_BUSCA_ATIVA = 2024;
export const ANO_INICIO_PRODUTIVIDADE = 2023;
