export const SGP_SELECT_COMPONENTE_CURRICULAR =
  'SGP_SELECT_COMPONENTE_CURRICULAR';
export const SGP_SELECT_ANO_LETIVO = 'SGP_SELECT_ANO_LETIVO';
export const SGP_SELECT_DRE = 'SGP_SELECT_DRE';
export const SGP_SELECT_UE = 'SGP_SELECT_UE';
export const SGP_SELECT_MODALIDADE = 'SGP_SELECT_MODALIDADE';
export const SGP_SELECT_SEMESTRE = 'SGP_SELECT_SEMESTRE';
export const SGP_SELECT_TURMA = 'SGP_SELECT_TURMA';
export const SGP_SELECT_BIMESTRE = 'SGP_SELECT_BIMESTRE';
export const SGP_SELECT_PERIODO_POR_COMPONENTE_CURRICULAR =
  'SGP_SELECT_PERIODO_POR_COMPONENTE_CURRICULAR';
export const SGP_SELECT_TIPO_PENDENCIA = 'SGP_SELECT_TIPO_PENDENCIA';
export const SGP_SELECT_NOME_TIPO_PENDENCIA = 'SGP_SELECT_NOME_TIPO_PENDENCIA';
