export const SGP_ALERT_JUSTIFICATIVA_PORCENTAGEM =
  'SGP_ALERT_JUSTIFICATIVA_PORCENTAGEM';
export const SGP_ALERT_ALERTA_PRINCIPAL = 'SGP_ALERT_ALERTA_PRINCIPAL';
export const SGP_ALERT_PODE_LANCAR_NOTA = 'SGP_ALERT_PODE_LANCAR_NOTA';
export const SGP_ALERT_PERIODO_FECHAMENTO = 'SGP_ALERT_PERIODO_FECHAMENTO';
