export const SGP_TABS_PRIMEIRO_BIMESTRE = 'SGP_TABS_PRIMEIRO_BIMESTRE';
export const SGP_TABS_SEGUNDO_BIMESTRE = 'SGP_TABS_SEGUNDO_BIMESTRE';
export const SGP_TABS_TERCEIRO_BIMESTRE = 'SGP_TABS_TERCEIRO_BIMESTRE';
export const SGP_TABS_QUARTO_BIMESTRE = 'SGP_TABS_QUARTO_BIMESTRE';
