name: CI/CD

on:
  push:
    branches: [ fix/pipeline-dev ]
  pull_request:
    branches: [  ]

jobs:
  docker:
    name: Docker
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        echo $docker_pass | docker login registry.sme.prefeitura.sp.gov.br -u $docker_user --password-stdin 
        docker build -t registry.sme.prefeitura.sp.gov.br/sgp/sme-sgp-webclient:$(${branch:11} | tr '/' '-') -f src/SME.SGP.WebClient/Dockerfile .
        docker push registry.sme.prefeitura.sp.gov.br/sgp/sme-sgp-webclient:$(${branch:11} | tr '/' '-')
      env: # https://docs.github.com/en/actions/reference/environment-variables
        docker_user: ${{ secrets.DOCKER_USER }}
        docker_pass: ${{ secrets.DOCKER_PASS }}
        branch: ${{ github.ref }}
